# Generated by Django 4.1.1 on 2022-10-05 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=50, verbose_name="Make")),
                ("modal", models.CharField(max_length=50, verbose_name="Modal")),
                ("year", models.CharField(max_length=50, verbose_name="Year")),
                ("logo", models.ImageField(upload_to="", verbose_name="Logo")),
                ("capacity", models.IntegerField(verbose_name="Capacity")),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "date_posted",
                    models.DateTimeField(auto_now=True, verbose_name="Date Posted"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.CharField(max_length=100, verbose_name="Price")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.car",
                        verbose_name="Car",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.city",
                        verbose_name="City",
                    ),
                ),
            ],
        ),
    ]
