# Generated by Django 4.1.1 on 2022-10-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="date_posted",
            field=models.DateTimeField(auto_now=True, verbose_name="Date Posted"),
        ),
        migrations.AddField(
            model_name="price",
            name="date_posted",
            field=models.DateTimeField(auto_now=True, verbose_name="Date Posted"),
        ),
    ]
