# Generated by Django 4.1.1 on 2022-10-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_car_date_posted_price_date_posted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="city",
        ),
        migrations.AddField(
            model_name="price",
            name="from_city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_city",
                to="pages.city",
                verbose_name="City",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="price",
            name="to_city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_city",
                to="pages.city",
                verbose_name="From City",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="price",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.car",
                verbose_name="To Car",
            ),
        ),
    ]
