# Generated by Django 4.1.1 on 2022-10-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_remove_price_city_price_from_city_price_to_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "date_posted",
                    models.DateTimeField(auto_now=True, verbose_name="Date Posted"),
                ),
            ],
        ),
    ]
