# Generated by Django 4.1.1 on 2022-10-08 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.type",
                verbose_name="Type",
            ),
            preserve_default=False,
        ),
    ]
