# Generated by Django 4.1.1 on 2022-10-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_contactus"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Content"),
        ),
    ]
